name: rocket_cli
description: A command-line tool for generating RocketModel classes from JSON for the flutter_rocket package.
version: 1.1.0
repository: https://github.com/JahezAcademy/flutter_rocket/tree/dev/rocket_cli
homepage: https://github.com/JahezAcademy/flutter_rocket

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dart_style: ^2.3.1
  args: ^2.4.2

executables:
  rocket_cli:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
